### ISSUE TITLE
Cannot edit allowances; After changing from unlimited to 1, cannot click "Okay", but cancel button works

### ISSUE THREAD

**Issue by spaceblankey** [TripleSpeeder/token-allowance-checker#34] opened 2020-03-05 03:29 UTC
![image](https://user-images.githubusercontent.com/11826113/75945109-71ef7500-5eed-11ea-97be-1a31633e33ed.png)

Cannot click the okay button, nothing happens. Cancel closes the box. Trying different values in the box results in the same problem (0,01,2,100).

Appears to only be the case for this spender or contract: 0x67dA490CFF3B23d8602eDc311B4d108C7EE82094 --Spender
0xEE85966b4974d3C6F71A2779cC3B6F53aFbc2B68 --Contract

As I can edit others, but not this one.

**Comment by TripleSpeeder** [comment] 2020-03-16 15:21
Thanks for the report @spaceblankey 
Can you confirm that this is still happening? I did some major refactoring and fixed several potential issues on the way, so maybe this has been resolved already.

If the issue still exists help me understand further:
You can edit Rare Chest allowance for other spender addresses, is this right? So it seems to be a specific problem with your owner address?

**Comment by TripleSpeeder** [comment] 2020-04-27 21:46
Closing this for now as I got no further reports or feedback. Please reopen if you can still reproduce this issue!

**Closed by TripleSpeeder** 2020-04-27 21:46 UTC
